"""FFmpeg composition script exporter.

Generates shell/PowerShell scripts that concatenate video clips, overlay
subtitles, and mix audio tracks for each episode.

Registered as exporter "ffmpeg" via hooks.register_exporter.
"""
from __future__ import annotations

import json
import platform
from pathlib import Path

from hooks import register_exporter


def export_ffmpeg(out_dir: str, ep_range: list[int] | None = None) -> list[Path]:
    """Generate FFmpeg compose scripts for specified episodes."""
    out = Path(out_dir)
    generated: list[Path] = []
    is_windows = platform.system() == "Windows"

    if ep_range is None:
        ep_dirs = sorted(out.glob("E*"))
        ep_range = []
        for d in ep_dirs:
            try:
                ep_range.append(int(d.name.lstrip("E")))
            except ValueError:
                pass

    for ep in ep_range:
        ctx_path = out / f"E{ep}" / "gen_context.json"
        if not ctx_path.is_file():
            continue

        try:
            ctx = json.loads(ctx_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue

        sb = ctx.get("storyboard") or {}
        shots = sb.get("shots") or []
        if not isinstance(shots, list) or not shots:
            continue

        concat_lines: list[str] = []
        for s in shots:
            if not isinstance(s, dict):
                continue
            sid = s.get("shot_id", "")
            if not sid:
                continue
            concat_lines.append(f"file 'shots/{sid}.mp4'")

        if not concat_lines:
            continue

        concat_list_path = out / f"E{ep}" / "concat_list.txt"
        concat_list_path.write_text("\n".join(concat_lines), encoding="utf-8")

        output = out / f"E{ep}" / f"E{ep}_composed.mp4"

        if is_windows:
            script = _build_ps1(ep, output)
            ext = ".ps1"
        else:
            script = _build_sh(ep, output)
            ext = ".sh"

        script_path = out / f"E{ep}" / f"compose{ext}"
        script_path.parent.mkdir(parents=True, exist_ok=True)
        script_path.write_text(script, encoding="utf-8")

        if not is_windows:
            script_path.chmod(0o755)

        generated.append(script_path)

    return generated


def _build_sh(ep: int, output: Path) -> str:
    output_path = str(output)
    return f"""#!/bin/bash
# Auto-generated by nuomi-drama-skills — Episode {ep}
# Usage: bash compose.sh
set -euo pipefail

cd "$(dirname "$0")"

ffmpeg -f concat -safe 0 -i concat_list.txt \\
  -vf "scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2" \\
  -c:v libx264 -preset medium -crf 23 \\
  -pix_fmt yuv420p \\
  -an \\
  {output_path}

echo "Done: {output_path}"
"""


def _build_ps1(ep: int, output: Path) -> str:
    output_path = str(output)
    return f"""# Auto-generated by nuomi-drama-skills — Episode {ep}
# Usage: .\\compose.ps1
$ErrorActionPreference = "Stop"

Set-Location "$PSScriptRoot"

ffmpeg -f concat -safe 0 -i concat_list.txt `
  -vf "scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2" `
  -c:v libx264 -preset medium -crf 23 `
  -pix_fmt yuv420p `
  -an `
  {output_path}

Write-Host "Done: {output_path}"
"""


register_exporter("ffmpeg", export_ffmpeg)
